version: 2
updates:
- package-ecosystem: maven
  directory: "/"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: org.elasticsearch:elasticsearch-x-content
    versions:
    - 7.12.0
  - dependency-name: org.elasticsearch:elasticsearch
    versions:
    - 7.12.0
  - dependency-name: org.elasticsearch.client:elasticsearch-rest-client
    versions:
    - 7.12.0
  - dependency-name: org.elasticsearch.client:elasticsearch-rest-high-level-client
    versions:
    - 7.12.0
  - dependency-name: io.netty:netty-transport
    versions:
    - 4.1.52.Final
    - 4.1.59.Final
    - 4.1.60.Final
    - 4.1.62.Final
  - dependency-name: io.netty:netty-resolver
    versions:
    - 4.1.52.Final
    - 4.1.59.Final
    - 4.1.60.Final
    - 4.1.62.Final
  - dependency-name: io.netty:netty-handler
    versions:
    - 4.1.52.Final
    - 4.1.59.Final
    - 4.1.60.Final
    - 4.1.62.Final
  - dependency-name: io.netty:netty-common
    versions:
    - 4.1.52.Final
    - 4.1.59.Final
    - 4.1.60.Final
    - 4.1.62.Final
  - dependency-name: io.netty:netty-codec-http
    versions:
    - 4.1.52.Final
    - 4.1.59.Final
    - 4.1.60.Final
    - 4.1.62.Final
  - dependency-name: io.netty:netty-codec
    versions:
    - 4.1.52.Final
    - 4.1.59.Final
    - 4.1.60.Final
    - 4.1.62.Final
  - dependency-name: io.netty:netty-buffer
    versions:
    - 4.1.52.Final
    - 4.1.59.Final
    - 4.1.60.Final
    - 4.1.62.Final
  - dependency-name: org.apache.lucene:lucene-facet
    versions:
    - 8.7.0
    - 8.8.0
  - dependency-name: org.apache.lucene:lucene-misc
    versions:
    - 8.7.0
    - 8.8.0
  - dependency-name: org.apache.lucene:lucene-memory
    versions:
    - 8.7.0
    - 8.8.0
  - dependency-name: org.apache.lucene:lucene-highlighter
    versions:
    - 8.7.0
    - 8.8.0
  - dependency-name: org.apache.lucene:lucene-suggest
    versions:
    - 8.7.0
    - 8.8.0
  - dependency-name: org.apache.lucene:lucene-queries
    versions:
    - 8.7.0
    - 8.8.0
  - dependency-name: org.apache.lucene:lucene-queryparser
    versions:
    - 8.7.0
    - 8.8.0
  - dependency-name: org.apache.lucene:lucene-analyzers-common
    versions:
    - 8.7.0
    - 8.8.0
  - dependency-name: org.apache.lucene:lucene-core
    versions:
    - 8.7.0
    - 8.8.0
